# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
  branches:
    include:
      - main    
     
pool:
  vmImage: 'ubuntu-latest'  
 
stages:
  - stage: E2ETests
    displayName: Run E2E Test on Main
    jobs:
      - job: Test
        displayName: Cypress.E2E
     
        steps:
          - task: NodeTool@0
            displayName: Install NodeJS
            inputs:
              versionSpec: '14.x'
         
          - script:
              npm install
              npx cypress run --browser chrome
            displayName: Build and run test
 
          - task: PublishTestResults@2
            displayName: Publish E2E test results
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: '*.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
              mergeTestResults: true
 

